In [13]:
import pandas as pd
import pyarrow.parquet as pq

In [9]:
df=pd.read_csv('measures.csv', sep=";")

In [10]:
df.head()

,measureID,measure,date_granularity,location_granularity,unit
0,1,Presence of Rift Valley Fever in country,Bi-Annual,Country,presence
1,2,Presence of FMD in country,Bi-Annual,Country,presence
2,3,Presence of LSD in country,Bi-Annual,Country,presence
3,4,Presence of PPR in country,Bi-Annual,Country,presence
4,5,Area of impact by locust,Weekly,District,km^2

In [11]:
df

,measureID,measure,date_granularity,location_granularity,unit
0,1,Presence of Rift Valley Fever in country,Bi-Annual,Country,presence
1,2,Presence of FMD in country,Bi-Annual,Country,presence
2,3,Presence of LSD in country,Bi-Annual,Country,presence
3,4,Presence of PPR in country,Bi-Annual,Country,presence
4,5,Area of impact by locust,Weekly,District,km^2
5,6,Price of maize,Monthly,District,local currency/kg
6,7,Price of rice,Monthly,District,local currency/kg
7,8,Price of beef,Monthly,District,local currency/kg
8,9,Price of milk,Monthly,District,local currency/l
9,10,Price of eggs,Monthly,District,local currency/kg
10,11,Price of beans,Monthly,District,local currency/kg
11,12,Production of maize,Yearly,Country,tonnes
12,13,Production of rice,Yearly,Country,tonnes
13,14,Production of millet,Yearly,Country,tonnes
14,15,Production of beans,Yearly,Country,tonnes
15,16,Production of wheat,Yearly,Country,tonnes
16,17,Market Access,Yearly,District,NaN
17,18,Fatalities related to conflict,Weekly,District,persons
18,19,Conflict Events,Weekly,District,incidents
19,20,Demand for milk,Yearly,District,tonnes
20,21,Demand for eggs,Yearly,District,tonnes
21,22,Demand for beef,Yearly,District,tonnes
22,23,Demand for poultry,Yearly,District,tonnes
23,24,Demand for mutton,Yearly,District,tonnes
24,25,Demand for pork,Yearly,District,tonnes
25,26,Population,Yearly,District,persons

In [12]:
df.to_parquet('measures_parquet',
              index = False)

In [15]:
 t = pq.read_table('measures_parquet')

In [18]:
print(t)

pyarrow.Table
measureID: int64
measure: string
date_granularity: string
location_granularity: string
unit : string
metadata
--------
{b'pandas': b'{"index_columns": [], "column_indexes": [], "columns": [{"name":'
            b' "measureID", "field_name": "measureID", "pandas_type": "int64",'
            b' "numpy_type": "int64", "metadata": null}, {"name": "measure", "'
            b'field_name": "measure", "pandas_type": "unicode", "numpy_type": '
            b'"object", "metadata": null}, {"name": "date_granularity", "field'
            b'_name": "date_granularity", "pandas_type": "unicode", "numpy_typ'
            b'e": "object", "metadata": null}, {"name": "location_granularity"'
            b', "field_name": "location_granularity", "pandas_type": "unicode"'
            b', "numpy_type": "object", "metadata": null}, {"name": "unit ", "'
            b'field_name": "unit ", "pandas_type": "unicode", "numpy_type": "o'
            b'bject", "metadata": null}], "pandas_version": "0.25.1"}'}